// The assets/ drop folder is user-owned; everything imports through these
// semantic names so a renamed or replaced drop is a one-file edit.
import wordmark from '../../assets/frost.png';
import wordmarkAlt from '../../assets/frostuwu.png';
import emblem from '../../assets/frost3.png';
import mark from '../../assets/frost2.png';
import badge from '../../assets/3232FROST.png';
import topo from '../../assets/frostbackground2.png';
// Rimeward (the dashboard + desktop app): generated by ops/rimeward-brand.mjs,
// the .svg imports are Astro components — <RimewardLockup class="…" />.
import RimewardMark from '../../assets/rimeward-mark.svg';
import RimewardLockup from '../../assets/rimeward-lockup.svg';

export { wordmark, wordmarkAlt, emblem, mark, badge, topo, RimewardMark, RimewardLockup };
